### ISSUE TITLE
Downloader encountered a problem that can't be solved: Downloader failed to get cookie from Sharepoint

### ISSUE THREAD

**Issue by jaum20** [axzxc1236/pySharepointDownloader#1]
How can I solve this?

`Downloader encountered a problem that can't be solved: Downloader failed to get cookie from Sharepoint`

**Comment by axzxc1236** [comment]
Without knowing the link you are trying to download, I am afraid I can't help much.

I just ran the test link included in config and it works for both password protected link and one without password.

Can you access the sharepoint link in browser in newly opened private browsing window?

**Comment by axzxc1236** [comment]
If you can open the link in your browser, these are steps that I might take:

1. run Program with test config once.
2. Change lines in sharepoint_rclone.conf with your sharepoint link and browser cookies (FedAuth field is required)
3. run `rclone config --config sharepoint_rclone.conf copy (.... parameters)`, doing so you bypassed using this program completely.

**Comment by jaum20** [comment]
> I just ran the test link included in config and it works for both password protected link and one without password.

Yes, those work for me too. I am trying to download an entire folder. Will this script work?

>Can you access the sharepoint link in browser in newly opened private browsing window?

yes, I can. The link structure is: https://name.sharepoint.com/:f:/s/groupname/xxxx...

**Comment by jaum20** [comment]
> If you can open the link in your browser, these are steps that I might take:
> 
> 1. run Program with test config once.
> 2. Change lines in sharepoint_rclone.conf with your sharepoint link and browser cookies (FedAuth field is required)
> 3. run `rclone config --config sharepoint_rclone.conf copy (.... parameters)`, doing so you bypassed using this program completely.

I get a error: ` Failed to copy: couldn't list files: 405 Method Not Allowed`

**Comment by axzxc1236** [comment]
>  I am trying to download an entire folder. Will this script work?

It has been working for me... well enough to down terabytes of files.

> The link structure is: https://name.sharepoint.com/:f:/s/groupname/xxxx

The link format looks like what I generated today...... and it works with my program.

I am sorry, but I have been trying sharepoint links that I can find on forums and I've failed to replicate your issue.

**Comment by jaum20** [comment]
> I am sorry, but I have been trying sharepoint links that I can find on forums and I've failed to replicate your issue.

Can I email you the link?

**Comment by axzxc1236** [comment]
Sure, you can email the link to axzxc1236@gmail.com.

**Comment by jaum20** [comment]
sent

**Comment by axzxc1236** [comment]
I tested the link and found out what's wrong, and get it fixed in https://github.com/axzxc1236/pySharepointDownloader/commit/e49f9b817e8270b31ff8a2ece82ad13fbede361c.

Please download new version of the script and check if it works.

**Comment by jaum20** [comment]
Still not working. 

```
Transferred:              0 B / 0 B, -, 0 B/s, ETA -
Elapsed time:         0.3s
2024-04-24 11:01:29,521: Completed 1 tasks, skipped 0 tasks
```


I checked the `sharepoint_rclone.conf` file and noted that there are spaces in the `url`. Can this be the problem?

**Comment by axzxc1236** [comment]
It shouldn't be the problem.... I tried your link again and it downloads on my system...

Can you tell me:

(1) which Operating system are you using
(2) what version show up using `python3 --version`
(2) what version show up using `rclone --version`

**Comment by jaum20** [comment]
1. Windows
2. `Python 3.12.0`
3. 
```
rclone v1.66.0
- os/version: Microsoft Windows 10 Enterprise 22H2 (64 bit)
- os/kernel: 10.0.19045.4291 (x86_64)
- os/type: windows
- os/arch: amd64
- go/version: go1.22.1
- go/linking: static
- go/tags: cmount
```

**Comment by axzxc1236** [comment]
The problem that causes rclone to download 0 files should be fixed by https://github.com/axzxc1236/pySharepointDownloader/commit/bd56044e3a9277a24221f9c1a9b397f77cf60a5c.

**Comment by jaum20** [comment]
Thank you. Its is working!
